/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/core/main-slider-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of slider images.
         * @description Returns a list of slider images
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of slider images */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MainSliderItem"][];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/statistic-block/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of data for the statistic block.
         * @description Returns a list of data for statistic block
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of data for statictic block */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatisticBlock"][];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/partners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of partners.
         * @description Returns a list of data for partners block
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of data for partners block */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partners"][];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/faq/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of FAQs (questions and answers).
         * @description Returns a list of data for the FAQ block
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of data for the FAQ block */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FAQs"][];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/educational-programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of educational programs.
         * @description Returns a list of data for the edu-programs block.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of data for the edu-programs block */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EducationalProgram"][];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/alumni/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of Alumni
         * @description Returns a list of Alumni, optionally filtered by graduation year
         */
        get: {
            parameters: {
                query?: {
                    /** @description Graduation year to filter alumni */
                    year?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of Alumni */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alumnus"][];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new Alumnus
         * @description Creates a new Alumnus with Ukrainian translation fields
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * @description Full name of the alumnus (Ukrainian)
                         * @example Іван Іваненко
                         */
                        full_name?: string;
                        /**
                         * @description Short bio or description (optional)
                         * @example Graduated in Computer Science.
                         */
                        text?: string;
                        /**
                         * @description Major field of study
                         * @example Computer Science
                         */
                        major?: string;
                        /**
                         * @description Degree obtained
                         * @example Bachelor
                         */
                        degree?: string;
                        /**
                         * @description Workplace (optional)
                         * @example Google
                         */
                        workplace?: string;
                        /**
                         * @description Position at workplace (optional)
                         * @example Software Engineer
                         */
                        position?: string;
                        /**
                         * Format: binary
                         * @description Profile image of the alumnus
                         */
                        image?: string;
                        /**
                         * @description Social links or other publications (optional)
                         * @example {
                         *       "instagram": "https://instagram.com/ivan",
                         *       "telegram": "https://t.me/ivan",
                         *       "facebook": "https://facebook.com/ivan"
                         *     }
                         */
                        links?: {
                            [key: string]: string;
                        };
                        /**
                         * Format: date
                         * @description Graduation date
                         * @example 2024-06-15
                         */
                        date_of_graduation?: string;
                    };
                };
            };
            responses: {
                /** @description Successfully created Alumnus */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 123 */
                            id?: number;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/alumni/years/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of graduation years
         * @description Returns a list of graduation years
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of alumni */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number[];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/core/alumni-slider-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of alumni slider objects.
         * @description Returns a list of alumni slider objects
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned a list of slider images */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlumniSliderItem"][];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login using Google OAuth2 with PKCE
         * @description 1) Send JSON body with:
         *        - `code` (authorization code received from Google after redirect)
         *        - `code_verifier` (PKCE code verifier generated on frontend)
         *     2) Backend exchanges the `code` and `code_verifier` for Google access token.
         *     3) User is created or updated in the local database, and app-specific access and refresh tokens are generated.
         *     4) **Access token is returned in the JSON response body.**
         *     5) **Refresh token is set as a secure HttpOnly cookie named `refresh_token`.** *This endpoint does NOT require an Authorization header (no token required) since it is the login endpoint.*
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Authorization code received from Google (provided by frontend) */
                        code: string;
                        /** @description PKCE code verifier matching the code_challenge sent initially */
                        code_verifier: string;
                    };
                };
            };
            responses: {
                /** @description Successfully authenticated, tokens issued */
                200: {
                    headers: {
                        /** @description Refresh token is set in a HttpOnly, Secure cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description OAuth2 access token to use in Authorization header */
                            access_token?: string;
                            /** @description Access token lifetime in seconds */
                            expires_in?: number;
                            /** @example Bearer */
                            token_type?: string;
                        };
                    };
                };
                /** @description Missing code or code_verifier, or Google token exchange error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token using refresh_token cookie
         * @description 1) Send POST with body:
         *        - `client_id=client_id`
         *        - `grant_type=refresh_token`
         *
         *     2) **Refresh token is NOT sent in the body; it is automatically read from the HttpOnly cookie `refresh_token`.**
         *     3) If the refresh token is valid, a new access token is returned in the response body.
         *     4) A new refresh token cookie is also set to replace the old one. *This endpoint does NOT require an Authorization header because refresh token is taken from the cookie.*
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /**
                         * @description Client token from API
                         * @enum {string}
                         */
                        client_id: "client_id";
                        /**
                         * @description Must be exactly `refresh_token`
                         * @enum {string}
                         */
                        grant_type: "refresh_token";
                    };
                };
            };
            responses: {
                /** @description Access token successfully refreshed */
                200: {
                    headers: {
                        /** @description Updated refresh token set in cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description New access token */
                            access_token?: string;
                            /** @description Access token lifetime in seconds */
                            expires_in?: number;
                            /** @example Bearer */
                            token_type?: string;
                        };
                    };
                };
                /** @description Invalid request or missing/invalid refresh token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user information
         * @description Returns information about the currently authenticated user.   Requires a valid `access` token via Authorization header.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned user info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Unauthorized or token missing/invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error during profile fetching */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user role
         * @description Returns information about role current user. (Required `access` token in headers for auth user)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully returned information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            role?: string;
                        };
                    };
                };
                /** @description Unauthorized or token missing/invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of events.
         * @description Returns list of the events.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event list successfully returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Events"][];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns details of a single event by its unique ID.
         * @description Returns a single event object by its unique ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique identifier of the event */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event object successfully returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Events"];
                    };
                };
                /** @description Bad request (invalid ID or malformed request) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of departments
         * @description Returns a list of departments
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Departments list successfully returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Departments"][];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns details of a single department by its unique ID.
         * @description Returns a single department object by its unique ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique identifier of the event */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Department object successfully returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentDetail"];
                    };
                };
                /** @description Bad request (invalid ID or malformed request) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Error code */
            code: string;
            /** @description Human readable error message */
            message: string;
        };
        MainSliderItem: {
            /** ID */
            readonly id?: number;
            /**
             * Image
             * Format: uri
             */
            readonly image?: string;
        };
        StatisticBlock: {
            /** ID */
            readonly id?: number;
            /** Title */
            readonly title?: string;
            /** Description */
            readonly description?: string;
            /** Start Value */
            readonly start_value?: number;
            /** Order */
            readonly order?: number;
        };
        User: {
            /** ID */
            readonly id?: number;
            /** First name */
            readonly first_name?: string;
            /** Last name */
            readonly last_name?: string;
            /**
             * Email
             * Format: email
             */
            readonly email?: string;
            /**
             * Avatar
             * Format: uri
             */
            readonly avatar?: string;
        };
        Events: {
            /** ID */
            readonly id?: number;
            /** Title */
            readonly title?: string;
            /** Body */
            readonly body?: string;
            /** HTML Body */
            readonly body_html?: string;
            category?: {
                id?: number;
                name?: string;
                /** @example (244,255,244,0.1) */
                rgb_color?: string;
            };
            /**
             * Format: date-time
             * @example 2025-06-30T11:39:01.957067Z
             */
            readonly created_at?: string;
            /**
             * Format: date-time
             * @example 2025-06-30T12:10:46.028492Z
             */
            readonly updated_at?: string;
        };
        Partners: {
            /** ID */
            readonly id?: number;
            /** Name */
            readonly name?: string;
            /**
             * Image
             * Format: uri
             */
            readonly image?: string;
            /**
             * Site url
             * Format: uri
             */
            readonly site_url?: string;
        };
        FAQs: {
            /** ID */
            readonly id?: number;
            /** Question */
            readonly question?: string;
            /** Question */
            readonly answer?: string;
        };
        CategorizedTag: {
            readonly id?: number;
            name?: string;
        };
        EducationalProgram: {
            /** ID */
            readonly id?: number;
            /** Program code */
            code?: string;
            /** Educational program name */
            name?: string;
            /** Subjects */
            readonly subject?: components["schemas"]["CategorizedTag"][];
            /** Education Forms */
            readonly education_forms?: components["schemas"]["CategorizedTag"][];
            /** Education Levels */
            readonly education_levels?: components["schemas"]["CategorizedTag"][];
        };
        ProgramSubject: {
            readonly id?: number;
            /** @description Subject name (translated) */
            name?: string;
            semester?: number;
            /** Format: float */
            credits?: number;
            /**
             * @description MN = Mandatory, EL = Elective
             * @enum {string}
             */
            type?: "MN" | "EL";
        };
        FacultyMember: {
            readonly id?: number;
            /** @description Full name (language-dependent) */
            name?: string;
            /** @description Role/position (language-dependent) */
            role?: string;
            /** @description Specialty (language-dependent) */
            specialty?: string;
            /** Format: uri */
            image?: string | null;
            /** Format: email */
            email?: string;
            audience?: string;
        };
        HeadOfDepartment: {
            readonly id?: number;
            /** @description Full name (language-dependent) */
            full_name?: string;
            /** @description Academic title/regalia (language-dependent) */
            regalia?: string;
            /** Format: email */
            email?: string | null;
            audience?: string | null;
        };
        DepartmentHistory: {
            readonly id?: number;
            /** @description Year or period label, e.g. '2004', '1970-ті', 'Сьогодні' */
            year?: string;
            /** @description Description of the historical event (translated) */
            text?: string;
        };
        EducationalProgramFull: components["schemas"]["EducationalProgram"] & {
            /** @description Translated description */
            description?: string;
            /** @description e.g. 'Бакалавр', 'Магістр' */
            degree?: string;
            /** @description e.g. 'Денна, заочна, дуальна' */
            form?: string;
            /** @description Duration in years */
            duration?: number | null;
            /** @description Total ECTS credits */
            total_credits?: number | null;
            budget_seats?: number | null;
            contract_seats?: number | null;
            subjects?: components["schemas"]["ProgramSubject"][];
            bachelor?: {
                code?: string;
                specialty?: string;
                program?: string;
            } | null;
            magistracy?: {
                code?: string;
                specialty?: string;
                program?: string;
            } | null;
            postgraduate?: {
                code?: string;
                specialty?: string;
                program?: string;
            } | null;
        };
        Departments: {
            /** ID */
            readonly id?: number;
            /** Department name */
            name?: string;
        };
        DepartmentDetail: {
            /** ID */
            readonly id?: number;
            /** @description Translated name of the department */
            name?: string;
            /** @description Translated description of the department */
            description?: string;
            /** @description Translated address of the department */
            address?: string;
            /** Format: email */
            email?: string;
            /**
             * Format: uri
             * @description Department group photo
             */
            image?: string | null;
            /** @description Department room number */
            room?: string;
            head_of_department?: components["schemas"]["HeadOfDepartment"][];
            /** @description Faculty members of the department */
            team?: components["schemas"]["FacultyMember"][];
            educational_program?: components["schemas"]["EducationalProgramFull"][];
            /** @description Chronological history of the department */
            history?: components["schemas"]["DepartmentHistory"][];
        };
        Alumnus: {
            /** ID */
            readonly id?: number;
            /** Full name */
            readonly full_name?: string;
            /** About student */
            readonly text?: string;
            /** Format: uri */
            readonly image?: string;
            /**
             * Created at
             * Format: date-time
             */
            readonly created_at?: string;
            /**
             * Date of graduation
             * Format: date
             */
            readonly date_of_graduation?: string;
            /**
             * Social links or publications
             * @description Dictionary of social/profile links
             * @example {
             *       "instagram": "https://instagram.com/example",
             *       "telegram": "https://t.me/example",
             *       "facebook": "https://facebook.com/example"
             *     }
             */
            links?: {
                [key: string]: string;
            };
            readonly major?: string;
            readonly degree?: string;
            readonly workplace?: string;
            readonly position?: string;
        };
        AlumniSliderItem: {
            /** ID */
            readonly id?: number;
            /**
             * Image
             * Format: uri
             */
            readonly image?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
